#! /bin/bash
# run vellum tests and lint the source

export PATH=`npm bin`:$PATH

if [[ "$1" == "--help" ]]; then
    echo "USAGE: $0 [TEST_GREP] [--no-lint]"
    exit
fi

qs=""
if [[ "$1" != "" && "$1" != -* ]]; then
    qs="$1"
    shift
fi

run_lint="true"
if [[ "$1" == "--no-lint" ]]; then
    run_lint="false"
    shift
fi

temp="/tmp/test-$$.tmp"

# run the tests
node_modules/mocha-headless-chrome/bin/start -f http://localhost:${VELLUM_PORT:-8088}/?grep="$qs" -t 500000 | tee
$temp

RESULT="${PIPESTATUS[0]}"
if grep -q "Parse error" $temp; then
    rm $temp
else
    rm $temp
    if [ "$RESULT" -ne 0 ]; then
        # stop on mocha-headless-chrome non-zero exit status (except parse error)
        # NOTE there may be edge cases where grep exits with non-zero
        # causing this script to exit prematurely
        exit 1
    fi
fi

if [[ "$run_lint" == "true" ]]; then
    npx eslint . && echo "linting passed"
fi
