#! /bin/bash
# run vellum tests and jshint the source

export PATH=`npm bin`:$PATH

if [[ "$1" == "--help" ]]; then
    echo "USAGE: $0 [TEST_GREP] [--no-jshint] [mocha-phantomjs-options]"
    exit
fi

qs=""
if [[ "$1" != "" && "$1" != -* ]]; then
    qs="$1"
    shift
fi

run_jshint="true"
if [[ "$1" == "--no-jshint" ]]; then
    run_jshint="false"
    shift
fi

temp="/tmp/test-$$.tmp"

# run the tests
phantomjs node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js 'index.html' spec "{\"grep\":\"$qs\",\"useColors\":true}" | tee $temp

RESULT="${PIPESTATUS[0]}"
if grep -q "Parse error" $temp; then
    rm $temp
else
    rm $temp
    if [ "$RESULT" -ne 0 ]; then
        # stop on mocha-phantomjs non-zero exit status (except parse error)
        # NOTE there may be edge cases where grep exits with non-zero
        # causing this script to exit prematurely
        exit 1
    fi
fi

if [[ "$run_jshint" == "true" ]]; then
    jshint src \
        && jshint --config tests/.jshintrc tests \
        && echo "jshint passed"
fi
