name: vellum tests
on:
  pull_request:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: |
        yarn_version=$(grep -Eo '^yarn@[^:]+' ./yarn.lock)
        npm install "$yarn_version"
        yarn install
        npm run testserver &
        make test
